dataset:
  name: ocean_das
  pair_id: [4]
model:
  activation: tanh
  branch_layers: 3
  epochs: 10000
  initialization: He normal
  lag: 45
  learning_rate: 0.002527854
  method: constant
  name: DeepONet
  neurons: 69
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 1