dataset:
  name: ocean_das
  pair_id: [3]
model:
  activation: relu
  branch_layers: 3
  epochs: 10000
  initialization: He normal
  lag: 74
  learning_rate: 0.087564892
  method: constant
  name: DeepONet
  neurons: 245
  optimizer: adam
  seed: 0
  trunk_layers: 3