dataset:
  name: ocean_das
  pair_id: [9]
model:
  activation: tanh
  branch_layers: 2
  epochs: 10000
  initialization: Glorot normal
  lag: 27
  learning_rate: 0.005251633
  method: constant
  name: DeepONet
  neurons: 34
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 1