dataset:
  name: ocean_das
  pair_id: [6]
model:
  activation: relu
  branch_layers: 2
  epochs: 10000
  initialization: Glorot normal
  lag: 65
  learning_rate: 0.0625557
  method: constant
  name: DeepONet
  neurons: 87
  optimizer: adam
  seed: 0
  trunk_layers: 3