dataset:
  name: ocean_das
  pair_id: [5]
model:
  activation: tanh
  branch_layers: 4
  epochs: 10000
  initialization: Glorot normal
  lag: 44
  learning_rate: 0.005535622
  method: constant
  name: DeepONet
  neurons: 85
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 2
